name: Build and Install GDAL with vcpkg

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # 或 ubuntu-latest, macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add vcpkg.json
      run: |
        echo '{
          "name": "gdal-vcpkg",
          "version": "1.0.0",
          "dependencies": [
            {
              "name": "gdal",
              "version>=": "3.10.3"
            }
          ]
        }' > vcpkg.json

    - name: Clone vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
            
    - name: Integrate and Install GDAL
      run: |
        cd vcpkg
        ./vcpkg integrate install
        ./vcpkg search gdal --featurepackages
        ./vcpkg install gdal --triplet x64-mingw-dynamic
        
    - name: Archive vcpkg artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vcpkg-packages
        path: |
          vcpkg/installed/
          vcpkg/packages/
        retention-days: 7  # 产物保留7天
